//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace netgsm
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://sms/", ConfigurationName="netgsm.smsnn")]
    public interface smsnn
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://sms/smsnn/sms_gonder_nnRequest", ReplyAction="http://sms/smsnn/sms_gonder_nnResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<netgsm.sms_gonder_nnResponse> sms_gonder_nnAsync(netgsm.sms_gonder_nnRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://sms/smsnn/smsGonderNNV2Request", ReplyAction="http://sms/smsnn/smsGonderNNV2Response")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<netgsm.smsGonderNNV2Response> smsGonderNNV2Async(netgsm.smsGonderNNV2Request request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://sms/smsnn/smsGonderNNV3Request", ReplyAction="http://sms/smsnn/smsGonderNNV3Response")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<netgsm.smsGonderNNV3Response> smsGonderNNV3Async(netgsm.smsGonderNNV3Request request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://sms/smsnn/sms_gonder_1nRequest", ReplyAction="http://sms/smsnn/sms_gonder_1nResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<netgsm.sms_gonder_1nResponse> sms_gonder_1nAsync(netgsm.sms_gonder_1nRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://sms/smsnn/smsGonder1NV2Request", ReplyAction="http://sms/smsnn/smsGonder1NV2Response")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<netgsm.smsGonder1NV2Response> smsGonder1NV2Async(netgsm.smsGonder1NV2Request request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://sms/smsnn/smsGonder1NV3Request", ReplyAction="http://sms/smsnn/smsGonder1NV3Response")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<netgsm.smsGonder1NV3Response> smsGonder1NV3Async(netgsm.smsGonder1NV3Request request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://sms/smsnn/krediRequest", ReplyAction="http://sms/smsnn/krediResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<netgsm.krediResponse> krediAsync(netgsm.krediRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://sms/smsnn/paketkampanyaRequest", ReplyAction="http://sms/smsnn/paketkampanyaResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<netgsm.paketkampanyaResponse> paketkampanyaAsync(netgsm.paketkampanyaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://sms/smsnn/raporRequest", ReplyAction="http://sms/smsnn/raporResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<netgsm.raporResponse> raporAsync(netgsm.raporRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://sms/smsnn/rapor_v2Request", ReplyAction="http://sms/smsnn/rapor_v2Response")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<netgsm.rapor_v2Response> rapor_v2Async(netgsm.rapor_v2Request request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://sms/smsnn/raporV3Request", ReplyAction="http://sms/smsnn/raporV3Response")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<netgsm.raporV3Response> raporV3Async(netgsm.raporV3Request request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://sms/smsnn/gondericiadlariRequest", ReplyAction="http://sms/smsnn/gondericiadlariResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<netgsm.gondericiadlariResponse> gondericiadlariAsync(netgsm.gondericiadlariRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://sms/smsnn/gelensmsRequest", ReplyAction="http://sms/smsnn/gelensmsResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<netgsm.gelensmsResponse> gelensmsAsync(netgsm.gelensmsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://sms/smsnn/gelensmsV2Request", ReplyAction="http://sms/smsnn/gelensmsV2Response")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<netgsm.gelensmsV2Response> gelensmsV2Async(netgsm.gelensmsV2Request request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="sms_gonder_nn", WrapperNamespace="http://sms/", IsWrapped=true)]
    public partial class sms_gonder_nnRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sms/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string username;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sms/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sms/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string company;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sms/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string header;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sms/", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute("msg", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string[] msg;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sms/", Order=5)]
        [System.Xml.Serialization.XmlElementAttribute("gsm", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string[] gsm;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sms/", Order=6)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string encoding;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sms/", Order=7)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string startdate;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sms/", Order=8)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string stopdate;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sms/", Order=9)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string bayikodu;
        
        public sms_gonder_nnRequest()
        {
        }
        
        public sms_gonder_nnRequest(string username, string password, string company, string header, string[] msg, string[] gsm, string encoding, string startdate, string stopdate, string bayikodu)
        {
            this.username = username;
            this.password = password;
            this.company = company;
            this.header = header;
            this.msg = msg;
            this.gsm = gsm;
            this.encoding = encoding;
            this.startdate = startdate;
            this.stopdate = stopdate;
            this.bayikodu = bayikodu;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="sms_gonder_nnResponse", WrapperNamespace="http://sms/", IsWrapped=true)]
    public partial class sms_gonder_nnResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="SMS", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Namespace="SMS")]
        public string @return;
        
        public sms_gonder_nnResponse()
        {
        }
        
        public sms_gonder_nnResponse(string @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="smsGonderNNV2", WrapperNamespace="http://sms/", IsWrapped=true)]
    public partial class smsGonderNNV2Request
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sms/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string username;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sms/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sms/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string header;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sms/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute("msg", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string[] msg;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sms/", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute("gsm", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string[] gsm;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sms/", Order=5)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string encoding;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sms/", Order=6)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string startdate;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sms/", Order=7)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string stopdate;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sms/", Order=8)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string bayikodu;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sms/", Order=9)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int filter;
        
        public smsGonderNNV2Request()
        {
        }
        
        public smsGonderNNV2Request(string username, string password, string header, string[] msg, string[] gsm, string encoding, string startdate, string stopdate, string bayikodu, int filter)
        {
            this.username = username;
            this.password = password;
            this.header = header;
            this.msg = msg;
            this.gsm = gsm;
            this.encoding = encoding;
            this.startdate = startdate;
            this.stopdate = stopdate;
            this.bayikodu = bayikodu;
            this.filter = filter;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="smsGonderNNV2Response", WrapperNamespace="http://sms/", IsWrapped=true)]
    public partial class smsGonderNNV2Response
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sms/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string @return;
        
        public smsGonderNNV2Response()
        {
        }
        
        public smsGonderNNV2Response(string @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="smsGonderNNV3", WrapperNamespace="http://sms/", IsWrapped=true)]
    public partial class smsGonderNNV3Request
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sms/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string username;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sms/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sms/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string header;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sms/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute("msg", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string[] msg;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sms/", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute("gsm", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string[] gsm;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sms/", Order=5)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string encoding;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sms/", Order=6)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string startdate;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sms/", Order=7)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string stopdate;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sms/", Order=8)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string bayikodu;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sms/", Order=9)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int filter;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sms/", Order=10)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string appkey;
        
        public smsGonderNNV3Request()
        {
        }
        
        public smsGonderNNV3Request(string username, string password, string header, string[] msg, string[] gsm, string encoding, string startdate, string stopdate, string bayikodu, int filter, string appkey)
        {
            this.username = username;
            this.password = password;
            this.header = header;
            this.msg = msg;
            this.gsm = gsm;
            this.encoding = encoding;
            this.startdate = startdate;
            this.stopdate = stopdate;
            this.bayikodu = bayikodu;
            this.filter = filter;
            this.appkey = appkey;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="smsGonderNNV3Response", WrapperNamespace="http://sms/", IsWrapped=true)]
    public partial class smsGonderNNV3Response
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sms/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string @return;
        
        public smsGonderNNV3Response()
        {
        }
        
        public smsGonderNNV3Response(string @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="sms_gonder_1n", WrapperNamespace="http://sms/", IsWrapped=true)]
    public partial class sms_gonder_1nRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sms/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string username;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sms/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sms/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string company;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sms/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string header;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sms/", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string msg;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sms/", Order=5)]
        [System.Xml.Serialization.XmlElementAttribute("gsm", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string[] gsm;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sms/", Order=6)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string encoding;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sms/", Order=7)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string startdate;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sms/", Order=8)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string stopdate;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sms/", Order=9)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string bayikodu;
        
        public sms_gonder_1nRequest()
        {
        }
        
        public sms_gonder_1nRequest(string username, string password, string company, string header, string msg, string[] gsm, string encoding, string startdate, string stopdate, string bayikodu)
        {
            this.username = username;
            this.password = password;
            this.company = company;
            this.header = header;
            this.msg = msg;
            this.gsm = gsm;
            this.encoding = encoding;
            this.startdate = startdate;
            this.stopdate = stopdate;
            this.bayikodu = bayikodu;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="sms_gonder_1nResponse", WrapperNamespace="http://sms/", IsWrapped=true)]
    public partial class sms_gonder_1nResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sms/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string @return;
        
        public sms_gonder_1nResponse()
        {
        }
        
        public sms_gonder_1nResponse(string @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="smsGonder1NV2", WrapperNamespace="http://sms/", IsWrapped=true)]
    public partial class smsGonder1NV2Request
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sms/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string username;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sms/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sms/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string header;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sms/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string msg;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sms/", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute("gsm", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string[] gsm;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sms/", Order=5)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string encoding;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sms/", Order=6)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string startdate;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sms/", Order=7)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string stopdate;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sms/", Order=8)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string bayikodu;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sms/", Order=9)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int filter;
        
        public smsGonder1NV2Request()
        {
        }
        
        public smsGonder1NV2Request(string username, string password, string header, string msg, string[] gsm, string encoding, string startdate, string stopdate, string bayikodu, int filter)
        {
            this.username = username;
            this.password = password;
            this.header = header;
            this.msg = msg;
            this.gsm = gsm;
            this.encoding = encoding;
            this.startdate = startdate;
            this.stopdate = stopdate;
            this.bayikodu = bayikodu;
            this.filter = filter;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="smsGonder1NV2Response", WrapperNamespace="http://sms/", IsWrapped=true)]
    public partial class smsGonder1NV2Response
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sms/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string @return;
        
        public smsGonder1NV2Response()
        {
        }
        
        public smsGonder1NV2Response(string @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="smsGonder1NV3", WrapperNamespace="http://sms/", IsWrapped=true)]
    public partial class smsGonder1NV3Request
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sms/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string username;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sms/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sms/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string header;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sms/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string msg;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sms/", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute("gsm", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string[] gsm;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sms/", Order=5)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string encoding;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sms/", Order=6)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string startdate;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sms/", Order=7)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string stopdate;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sms/", Order=8)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string bayikodu;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sms/", Order=9)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int filter;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sms/", Order=10)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string appkey;
        
        public smsGonder1NV3Request()
        {
        }
        
        public smsGonder1NV3Request(string username, string password, string header, string msg, string[] gsm, string encoding, string startdate, string stopdate, string bayikodu, int filter, string appkey)
        {
            this.username = username;
            this.password = password;
            this.header = header;
            this.msg = msg;
            this.gsm = gsm;
            this.encoding = encoding;
            this.startdate = startdate;
            this.stopdate = stopdate;
            this.bayikodu = bayikodu;
            this.filter = filter;
            this.appkey = appkey;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="smsGonder1NV3Response", WrapperNamespace="http://sms/", IsWrapped=true)]
    public partial class smsGonder1NV3Response
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sms/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string @return;
        
        public smsGonder1NV3Response()
        {
        }
        
        public smsGonder1NV3Response(string @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="kredi", WrapperNamespace="http://sms/", IsWrapped=true)]
    public partial class krediRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sms/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string username;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sms/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string password;
        
        public krediRequest()
        {
        }
        
        public krediRequest(string username, string password)
        {
            this.username = username;
            this.password = password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="krediResponse", WrapperNamespace="http://sms/", IsWrapped=true)]
    public partial class krediResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sms/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string @return;
        
        public krediResponse()
        {
        }
        
        public krediResponse(string @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="paketkampanya", WrapperNamespace="http://sms/", IsWrapped=true)]
    public partial class paketkampanyaRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sms/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string username;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sms/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string password;
        
        public paketkampanyaRequest()
        {
        }
        
        public paketkampanyaRequest(string username, string password)
        {
            this.username = username;
            this.password = password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="paketkampanyaResponse", WrapperNamespace="http://sms/", IsWrapped=true)]
    public partial class paketkampanyaResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sms/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string @return;
        
        public paketkampanyaResponse()
        {
        }
        
        public paketkampanyaResponse(string @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="rapor", WrapperNamespace="http://sms/", IsWrapped=true)]
    public partial class raporRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sms/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string username;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sms/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sms/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string bulkid;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sms/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int status;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sms/", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int version;
        
        public raporRequest()
        {
        }
        
        public raporRequest(string username, string password, string bulkid, int status, int version)
        {
            this.username = username;
            this.password = password;
            this.bulkid = bulkid;
            this.status = status;
            this.version = version;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="raporResponse", WrapperNamespace="http://sms/", IsWrapped=true)]
    public partial class raporResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sms/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string @return;
        
        public raporResponse()
        {
        }
        
        public raporResponse(string @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="rapor_v2", WrapperNamespace="http://sms/", IsWrapped=true)]
    public partial class rapor_v2Request
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sms/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string username;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sms/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sms/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string bulkid;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sms/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int status;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sms/", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int version;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sms/", Order=5)]
        [System.Xml.Serialization.XmlElementAttribute("telno", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string[] telno;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sms/", Order=6)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int detail;
        
        public rapor_v2Request()
        {
        }
        
        public rapor_v2Request(string username, string password, string bulkid, int status, int version, string[] telno, int detail)
        {
            this.username = username;
            this.password = password;
            this.bulkid = bulkid;
            this.status = status;
            this.version = version;
            this.telno = telno;
            this.detail = detail;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="rapor_v2Response", WrapperNamespace="http://sms/", IsWrapped=true)]
    public partial class rapor_v2Response
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sms/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string @return;
        
        public rapor_v2Response()
        {
        }
        
        public rapor_v2Response(string @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="raporV3", WrapperNamespace="http://sms/", IsWrapped=true)]
    public partial class raporV3Request
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sms/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string username;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sms/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sms/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string bulkid;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sms/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute("telno", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string[] telno;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sms/", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string header;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sms/", Order=5)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string startdate;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sms/", Order=6)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string stopdate;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sms/", Order=7)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int type;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sms/", Order=8)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int status;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sms/", Order=9)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int detail;
        
        public raporV3Request()
        {
        }
        
        public raporV3Request(string username, string password, string bulkid, string[] telno, string header, string startdate, string stopdate, int type, int status, int detail)
        {
            this.username = username;
            this.password = password;
            this.bulkid = bulkid;
            this.telno = telno;
            this.header = header;
            this.startdate = startdate;
            this.stopdate = stopdate;
            this.type = type;
            this.status = status;
            this.detail = detail;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="raporV3Response", WrapperNamespace="http://sms/", IsWrapped=true)]
    public partial class raporV3Response
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sms/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string @return;
        
        public raporV3Response()
        {
        }
        
        public raporV3Response(string @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="gondericiadlari", WrapperNamespace="http://sms/", IsWrapped=true)]
    public partial class gondericiadlariRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sms/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string username;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sms/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string password;
        
        public gondericiadlariRequest()
        {
        }
        
        public gondericiadlariRequest(string username, string password)
        {
            this.username = username;
            this.password = password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="gondericiadlariResponse", WrapperNamespace="http://sms/", IsWrapped=true)]
    public partial class gondericiadlariResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sms/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string @return;
        
        public gondericiadlariResponse()
        {
        }
        
        public gondericiadlariResponse(string @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="gelensms", WrapperNamespace="http://sms/", IsWrapped=true)]
    public partial class gelensmsRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sms/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string username;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sms/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string password;
        
        public gelensmsRequest()
        {
        }
        
        public gelensmsRequest(string username, string password)
        {
            this.username = username;
            this.password = password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="gelensmsResponse", WrapperNamespace="http://sms/", IsWrapped=true)]
    public partial class gelensmsResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sms/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string @return;
        
        public gelensmsResponse()
        {
        }
        
        public gelensmsResponse(string @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="gelensmsV2", WrapperNamespace="http://sms/", IsWrapped=true)]
    public partial class gelensmsV2Request
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sms/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string username;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sms/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sms/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string startdate;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sms/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string stopdate;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sms/", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int type;
        
        public gelensmsV2Request()
        {
        }
        
        public gelensmsV2Request(string username, string password, string startdate, string stopdate, int type)
        {
            this.username = username;
            this.password = password;
            this.startdate = startdate;
            this.stopdate = stopdate;
            this.type = type;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="gelensmsV2Response", WrapperNamespace="http://sms/", IsWrapped=true)]
    public partial class gelensmsV2Response
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sms/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string @return;
        
        public gelensmsV2Response()
        {
        }
        
        public gelensmsV2Response(string @return)
        {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public interface smsnnChannel : netgsm.smsnn, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public partial class smsnnClient : System.ServiceModel.ClientBase<netgsm.smsnn>, netgsm.smsnn
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public smsnnClient() : 
                base(smsnnClient.GetDefaultBinding(), smsnnClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.smsnnPort.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public smsnnClient(EndpointConfiguration endpointConfiguration) : 
                base(smsnnClient.GetBindingForEndpoint(endpointConfiguration), smsnnClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public smsnnClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(smsnnClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public smsnnClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(smsnnClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public smsnnClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<netgsm.sms_gonder_nnResponse> netgsm.smsnn.sms_gonder_nnAsync(netgsm.sms_gonder_nnRequest request)
        {
            return base.Channel.sms_gonder_nnAsync(request);
        }
        
        public System.Threading.Tasks.Task<netgsm.sms_gonder_nnResponse> sms_gonder_nnAsync(string username, string password, string company, string header, string[] msg, string[] gsm, string encoding, string startdate, string stopdate, string bayikodu)
        {
            netgsm.sms_gonder_nnRequest inValue = new netgsm.sms_gonder_nnRequest();
            inValue.username = username;
            inValue.password = password;
            inValue.company = company;
            inValue.header = header;
            inValue.msg = msg;
            inValue.gsm = gsm;
            inValue.encoding = encoding;
            inValue.startdate = startdate;
            inValue.stopdate = stopdate;
            inValue.bayikodu = bayikodu;
            return ((netgsm.smsnn)(this)).sms_gonder_nnAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<netgsm.smsGonderNNV2Response> netgsm.smsnn.smsGonderNNV2Async(netgsm.smsGonderNNV2Request request)
        {
            return base.Channel.smsGonderNNV2Async(request);
        }
        
        public System.Threading.Tasks.Task<netgsm.smsGonderNNV2Response> smsGonderNNV2Async(string username, string password, string header, string[] msg, string[] gsm, string encoding, string startdate, string stopdate, string bayikodu, int filter)
        {
            netgsm.smsGonderNNV2Request inValue = new netgsm.smsGonderNNV2Request();
            inValue.username = username;
            inValue.password = password;
            inValue.header = header;
            inValue.msg = msg;
            inValue.gsm = gsm;
            inValue.encoding = encoding;
            inValue.startdate = startdate;
            inValue.stopdate = stopdate;
            inValue.bayikodu = bayikodu;
            inValue.filter = filter;
            return ((netgsm.smsnn)(this)).smsGonderNNV2Async(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<netgsm.smsGonderNNV3Response> netgsm.smsnn.smsGonderNNV3Async(netgsm.smsGonderNNV3Request request)
        {
            return base.Channel.smsGonderNNV3Async(request);
        }
        
        public System.Threading.Tasks.Task<netgsm.smsGonderNNV3Response> smsGonderNNV3Async(string username, string password, string header, string[] msg, string[] gsm, string encoding, string startdate, string stopdate, string bayikodu, int filter, string appkey)
        {
            netgsm.smsGonderNNV3Request inValue = new netgsm.smsGonderNNV3Request();
            inValue.username = username;
            inValue.password = password;
            inValue.header = header;
            inValue.msg = msg;
            inValue.gsm = gsm;
            inValue.encoding = encoding;
            inValue.startdate = startdate;
            inValue.stopdate = stopdate;
            inValue.bayikodu = bayikodu;
            inValue.filter = filter;
            inValue.appkey = appkey;
            return ((netgsm.smsnn)(this)).smsGonderNNV3Async(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<netgsm.sms_gonder_1nResponse> netgsm.smsnn.sms_gonder_1nAsync(netgsm.sms_gonder_1nRequest request)
        {
            return base.Channel.sms_gonder_1nAsync(request);
        }
        
        public System.Threading.Tasks.Task<netgsm.sms_gonder_1nResponse> sms_gonder_1nAsync(string username, string password, string company, string header, string msg, string[] gsm, string encoding, string startdate, string stopdate, string bayikodu)
        {
            netgsm.sms_gonder_1nRequest inValue = new netgsm.sms_gonder_1nRequest();
            inValue.username = username;
            inValue.password = password;
            inValue.company = company;
            inValue.header = header;
            inValue.msg = msg;
            inValue.gsm = gsm;
            inValue.encoding = encoding;
            inValue.startdate = startdate;
            inValue.stopdate = stopdate;
            inValue.bayikodu = bayikodu;
            return ((netgsm.smsnn)(this)).sms_gonder_1nAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<netgsm.smsGonder1NV2Response> netgsm.smsnn.smsGonder1NV2Async(netgsm.smsGonder1NV2Request request)
        {
            return base.Channel.smsGonder1NV2Async(request);
        }
        
        public System.Threading.Tasks.Task<netgsm.smsGonder1NV2Response> smsGonder1NV2Async(string username, string password, string header, string msg, string[] gsm, string encoding, string startdate, string stopdate, string bayikodu, int filter)
        {
            netgsm.smsGonder1NV2Request inValue = new netgsm.smsGonder1NV2Request();
            inValue.username = username;
            inValue.password = password;
            inValue.header = header;
            inValue.msg = msg;
            inValue.gsm = gsm;
            inValue.encoding = encoding;
            inValue.startdate = startdate;
            inValue.stopdate = stopdate;
            inValue.bayikodu = bayikodu;
            inValue.filter = filter;
            return ((netgsm.smsnn)(this)).smsGonder1NV2Async(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<netgsm.smsGonder1NV3Response> netgsm.smsnn.smsGonder1NV3Async(netgsm.smsGonder1NV3Request request)
        {
            return base.Channel.smsGonder1NV3Async(request);
        }
        
        public System.Threading.Tasks.Task<netgsm.smsGonder1NV3Response> smsGonder1NV3Async(string username, string password, string header, string msg, string[] gsm, string encoding, string startdate, string stopdate, string bayikodu, int filter, string appkey)
        {
            netgsm.smsGonder1NV3Request inValue = new netgsm.smsGonder1NV3Request();
            inValue.username = username;
            inValue.password = password;
            inValue.header = header;
            inValue.msg = msg;
            inValue.gsm = gsm;
            inValue.encoding = encoding;
            inValue.startdate = startdate;
            inValue.stopdate = stopdate;
            inValue.bayikodu = bayikodu;
            inValue.filter = filter;
            inValue.appkey = appkey;
            return ((netgsm.smsnn)(this)).smsGonder1NV3Async(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<netgsm.krediResponse> netgsm.smsnn.krediAsync(netgsm.krediRequest request)
        {
            return base.Channel.krediAsync(request);
        }
        
        public System.Threading.Tasks.Task<netgsm.krediResponse> krediAsync(string username, string password)
        {
            netgsm.krediRequest inValue = new netgsm.krediRequest();
            inValue.username = username;
            inValue.password = password;
            return ((netgsm.smsnn)(this)).krediAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<netgsm.paketkampanyaResponse> netgsm.smsnn.paketkampanyaAsync(netgsm.paketkampanyaRequest request)
        {
            return base.Channel.paketkampanyaAsync(request);
        }
        
        public System.Threading.Tasks.Task<netgsm.paketkampanyaResponse> paketkampanyaAsync(string username, string password)
        {
            netgsm.paketkampanyaRequest inValue = new netgsm.paketkampanyaRequest();
            inValue.username = username;
            inValue.password = password;
            return ((netgsm.smsnn)(this)).paketkampanyaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<netgsm.raporResponse> netgsm.smsnn.raporAsync(netgsm.raporRequest request)
        {
            return base.Channel.raporAsync(request);
        }
        
        public System.Threading.Tasks.Task<netgsm.raporResponse> raporAsync(string username, string password, string bulkid, int status, int version)
        {
            netgsm.raporRequest inValue = new netgsm.raporRequest();
            inValue.username = username;
            inValue.password = password;
            inValue.bulkid = bulkid;
            inValue.status = status;
            inValue.version = version;
            return ((netgsm.smsnn)(this)).raporAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<netgsm.rapor_v2Response> netgsm.smsnn.rapor_v2Async(netgsm.rapor_v2Request request)
        {
            return base.Channel.rapor_v2Async(request);
        }
        
        public System.Threading.Tasks.Task<netgsm.rapor_v2Response> rapor_v2Async(string username, string password, string bulkid, int status, int version, string[] telno, int detail)
        {
            netgsm.rapor_v2Request inValue = new netgsm.rapor_v2Request();
            inValue.username = username;
            inValue.password = password;
            inValue.bulkid = bulkid;
            inValue.status = status;
            inValue.version = version;
            inValue.telno = telno;
            inValue.detail = detail;
            return ((netgsm.smsnn)(this)).rapor_v2Async(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<netgsm.raporV3Response> netgsm.smsnn.raporV3Async(netgsm.raporV3Request request)
        {
            return base.Channel.raporV3Async(request);
        }
        
        public System.Threading.Tasks.Task<netgsm.raporV3Response> raporV3Async(string username, string password, string bulkid, string[] telno, string header, string startdate, string stopdate, int type, int status, int detail)
        {
            netgsm.raporV3Request inValue = new netgsm.raporV3Request();
            inValue.username = username;
            inValue.password = password;
            inValue.bulkid = bulkid;
            inValue.telno = telno;
            inValue.header = header;
            inValue.startdate = startdate;
            inValue.stopdate = stopdate;
            inValue.type = type;
            inValue.status = status;
            inValue.detail = detail;
            return ((netgsm.smsnn)(this)).raporV3Async(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<netgsm.gondericiadlariResponse> netgsm.smsnn.gondericiadlariAsync(netgsm.gondericiadlariRequest request)
        {
            return base.Channel.gondericiadlariAsync(request);
        }
        
        public System.Threading.Tasks.Task<netgsm.gondericiadlariResponse> gondericiadlariAsync(string username, string password)
        {
            netgsm.gondericiadlariRequest inValue = new netgsm.gondericiadlariRequest();
            inValue.username = username;
            inValue.password = password;
            return ((netgsm.smsnn)(this)).gondericiadlariAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<netgsm.gelensmsResponse> netgsm.smsnn.gelensmsAsync(netgsm.gelensmsRequest request)
        {
            return base.Channel.gelensmsAsync(request);
        }
        
        public System.Threading.Tasks.Task<netgsm.gelensmsResponse> gelensmsAsync(string username, string password)
        {
            netgsm.gelensmsRequest inValue = new netgsm.gelensmsRequest();
            inValue.username = username;
            inValue.password = password;
            return ((netgsm.smsnn)(this)).gelensmsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<netgsm.gelensmsV2Response> netgsm.smsnn.gelensmsV2Async(netgsm.gelensmsV2Request request)
        {
            return base.Channel.gelensmsV2Async(request);
        }
        
        public System.Threading.Tasks.Task<netgsm.gelensmsV2Response> gelensmsV2Async(string username, string password, string startdate, string stopdate, int type)
        {
            netgsm.gelensmsV2Request inValue = new netgsm.gelensmsV2Request();
            inValue.username = username;
            inValue.password = password;
            inValue.startdate = startdate;
            inValue.stopdate = stopdate;
            inValue.type = type;
            return ((netgsm.smsnn)(this)).gelensmsV2Async(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.smsnnPort))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.smsnnPort))
            {
                return new System.ServiceModel.EndpointAddress("http://soap.netgsm.com.tr:8080/Sms_webservis/SMS");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return smsnnClient.GetBindingForEndpoint(EndpointConfiguration.smsnnPort);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return smsnnClient.GetEndpointAddress(EndpointConfiguration.smsnnPort);
        }
        
        public enum EndpointConfiguration
        {
            
            smsnnPort,
        }
    }
}
